includes/admin-page.php
readme.txt
redis-cache.php

The current version of the plugin appears in the Tools menu of every
site within a WordPress Multisite installation. In the case of a
Multisite installation, the administration options should only be
available to users with the Manage Network Options capability, and the
settings page should show within the Network section of the admin panel.
Note: I've also updated all calls to the admin_url function to network_admin_url. This is necessary for the plugin to work on WordPress Multisite installations, and simply reverts to the expected admin_url function if the installation is not multisite.

Add support for WordPress Multisite installations.

---

includes/object-cache.php

`advanced-cache.php` should have full access to the object cache, but at that point in execution the `maybe_unserialize` function has not been loaded yet.
For example, see: https://github.com/WordPress/WordPress/blob/master/wp-settings.php#L63-L72
This will allow batcache users to use this Redis Object Cache as a backend. fixes #9

provide local serialization functions.

---

includes/object-cache.php

Modified object cache to use `WP_CONTENT_DIR` instead `dirname( __FILE__)`. This fixes an issue where the object cache couldn't find the Predis library. The cause was the fact that `object-cache.php` was symlinked into `wp-content`. `dirname( __FILE__)` would resolve to the wrong location.

Use WordPress constant to load Predis library

---

includes/object-cache.php

There are currently three possible Redis clients that handle connections in different
ways and this has lead to a disconnect with how connections are handled.  This pull
request adds a bit of consistency when connecting to the Redis server.
To reproduce this issue you'll need to set your `WP_REDIS_CLIENT` to pecl and then
run your application without starting your Redis server. (this is an easy way to
guarantee a failed connection)
Previously only the hhvm client would check the success of the connect call while the
other two clients just assumed a connection occurred.
Proposed solution is to remove the explicit checking from the hhvm client so it's
inline with the behavior of the other two clients.  After we've set up our connection
but before we leave the try block we'll attempt to ping …

Fixing crash that occurs when connection fails

---

includes/object-cache.php

The object cache can be used inside of an `advanced-cache.php` dropin, but that also means that the object cache can be loaded early enough that most of Core hasn't been included yet, notably the actions and filters callbacks.
Checking that Core functions exist first avoids fatal errors with plugins like Batcache, or any other `advanced-cache.php` dropin that leverages the object cache.

Check core functions exist

---

includes/object-cache.php

Fixes #36 
This is still not 100% accurate because one could still rename the directory of the plugin itself, but it fixes the problem when the plugin dir has been moved outside of `wp-content`.

Change WP_CONTENT_DIR.'/plugins' to WP_PLUGIN_DIR

---

includes/object-cache.php

[1]: https://wordpress.org/support/topic/make-function-public-instead-of-private?replies=5
ElasticPress issue made more properties public. I'm not sure if it's necessary here or not. Perhaps makes sense to just go on-demand, one at a time.

Make WP_Object_Cache::$cache visibility public, fix WP-CLI etc. compatibility [1]

---

README.md
includes/object-cache.php

See discussion in #52.
This patch seems to be working well on my production box. I think it's good to go for my use-case. I haven't tested it with multi-site and I haven't tested it with YUUGE numbers of keys, but I have tested it with 400K+ keys and it took < 1 second to flush them.
Yay lua.

Flush cache with key prefix

---

includes/object-cache.php

This solution did solve our problem with creation of 100000+ keys after few hours of caching.
That happend because the wordpress does cache the terms for a day and you cannot change that as it is in the core.
Currently we have around 10K keys and the website speed is very fast.
FYI it does keep the default expiration value if you don't define the custom TTL.

Force expiration time for keys higher than zero exporation time

---

README.md
includes/diagnostics.php
includes/object-cache.php
includes/servers-list.php
readme.txt
redis-cache.php

Fixes problems with Redis Sentinel support.
I opted to add a new constant: WP_REDIS_SENTINELS to reflect the fact that predis expects to be passed the sentinels, and then fetches the server configs from the sentinels. This has the added advantage of not being dependent on the order the elseifs come in.

Extend and debug sentinel support

---

.travis.yml
includes/object-cache.php
phpunit.xml
tests/ObjectCacheTest.php
tests/bootstrap.php

A warning is generated when using a `RedisCluster` as the datasource for object cache with PECL Redis:
```
PHP Warning:  RedisCluster::ping() expects exactly 1 parameter, 0 given in /var/www/sportshub/releases/20180402235221/web/app/object-cache.php on line 494
```
This PR updates object-cache.php to ping with a host when in cluster mode. This avoids continuous PHP warnings in logs. I chose `WP_REDIS_HOST` as the constant to use since it's required in single node implementations and makes sense if you're using a hosting provider that only requires you know the endpoint to a single server to make use of an entire Redis Cluster, like AWS: https://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Endpoints.html#Endpoints.Find.RedisCluster
Of course we could use a different constant, or …

Fix RedisCluster warnings

---

README.md
includes/object-cache.php
readme.txt

igbinary serializer is faster than php's serialize() and it also
reduces stored data converting them into a binary form.
This commit brings a new WP_REDIS_IGBINARY constant which enables
igbinary serializer for Redis object cache.

igbinary serializer support is added.

---

includes/object-cache.php

Shouldn't match the `redis_object_cache_get` action. Renaming to
`redis_object_cache_get_value`
Fixes #90

Rename `redis_object_cache_get` filter

---

includes/object-cache.php

This plugin adds a filter to allowing the customization of the cache expiration setting depending on the inserted key/value in the database.
Using this, we could solve problems like the one described in https://wordpress.org/support/topic/expiration-date-5/

Adds filter to customize the cache expiration

---

README.md
includes/diagnostics.php
includes/object-cache.php

Redis-Object-Cache plug-in does not support redis-cluster adequately. It is wrong to operate the cluster in the wrong way. You use redis-cluster in the same way as singleton, because the characteristics of redis-cluster determine that some operations are invalid, such as ping, modifying the following code of object-cache.php or diagnostics.php to recover from failure.
- The use of PING command was removed and bug was fixed
- In addition, since redis-cluster mode cannot select database db numbers greater than 0, it is not meaningful to explicitly specify database db number operations in redis-cluster mode. I have changed the relevant parts of redis object cache documents, please update them.

The use of PING command was removed and bug was fixed.

---

README.md
includes/diagnostics.php
includes/object-cache.php
readme.txt

- Introduced the ability to add groups that will be ignored once a `wp_cache_flush` is requested
- Added new constant `WP_REDIS_UNFLUSHABLE_GROUPS`
- Changed the lua-script from using the `KEYS` command in favour of the preferable an non blocking `SCAN`
Tested on WordPress 5.2, PHP 7.2 and Redis 5.0.5

added unflushable groups functionality

---

.gitignore
includes/object-cache.php

Replaced the `lua_flush_script` method with a method returning a closure using the `unflushable_groups` property as lua-argument and differentiating between `pecl` and `predis` argument order of the respective `eval` methods.

more secure flush scripts

---

includes/object-cache.php

As mentioned in https://github.com/tillkruss/redis-cache/issues/123 plesk ships with phpredis version 3.0.0. As this version only supports 5 arguments for the redis `connection` method trying to call it with the 6th argument (retry_timeout) will result in a silent connection failure.
Digging into the phpredis source I found that the 6th argument was introduced in version 3.1.3 so this fix checks the installed version to that specific one and adds the 6th argument only if applicable.

Plesk phpredis fix

---

includes/object-cache.php

This is a small addition to allow gathering better diagnosis stats from cache actions. 
There is currently no way to tally the total amount of time spent making/getting cache requests.

Add execution times to hooks

---

includes/object-cache.php

This PR fix the LUA error, reported in issue #126 
`(error) ERR Error running script (call to f_523831630e0cc0dbf20c9141913c81f1bec591ba): @user_script:9: @user_script: 9: Write commands not allowed after non deterministic commands. Call redis.replicate_commands() at the start of your script in order to switch to single commands replication mode.`
PS: I don't know if this is the correct solution, I don't have much knowledge of redis, I try to read https://redis.io/commands/eval but I can't figure out.

Flush don't work with WP_REDIS_SELECTIVE_FLUSH set to TRUE (issue #126)

---

includes/diagnostics.php
includes/object-cache.php
redis-cache.php

As mentioned in https://github.com/tillkruss/redis-cache/pull/127
Added a version check to the `redis.replicate_commands()` LUA command as it is not needed in redis versions prior to 3.2 and since 5.0.
Additionally the actual redis version was not tracked before so I added the functionality and displayed it in the diagnostics section.

added lua script redis version check

---

includes/object-cache.php

Fix for https://github.com/tillkruss/redis-cache/issues/130
Chose the simpler method of removing the `strtolower` function as it will lower complexity in favor of transforming the salt in the LUA scripts as well.

Removed strtolower in build key method to fix LUA scripts

---

includes/object-cache.php

If notices are shown on pages, the application can break due to "headers already sent" PHP error.
This fix the problem.

hide notice on missing read_timeout parameter

---

includes/object-cache.php

**fixed**
when run "wp cache flush" and WP_REDIS_SELECTIVE_FLUSH set as true, the Redis fails to flush a cache due to salt contains a glob pattern.
**added**
glob_quote.

wp cache flush failed due to glob pattern in salt when selective_flush set as true

---

includes/object-cache.php

as per https://github.com/tillkruss/redis-cache/issues/164
Implemented group sanitization so that via configuration constants defined groups do appear sanitized in the plugin diagnostics section.
While implementing I also added some utility methods that should improve code readability: `is_ignored_group`, `is_global_group` and `is_unflushable_group`
Additionally it might be a good idea to implement some kind of warning in the settings page that a group using an illegal character was defined.

Added group sanitization

---

includes/object-cache.php

HI @tillkruss,
we use Redis with sentinel on our infrastructure and I notice that the DB selected is already the 0 even if we have set the WP_REDIS_DATABASE with a different value.
I see that predis library support the database choice https://github.com/nrk/predis/issues/291# and I added the $options['parameters']['database'] = $parameters['database']; in the same way of WP_REDIS_PASSWORD and it works.
Thanks in advance.
Fabio

fix support database selection with sentinel

---

readme.txt

Replaced sections **Connection Parameters**, **Configuration Options** and **Replication & Clustering** with links to the Wiki to avoid duplicate information storage.
Left **Installation** section as it is its own tab in the WordPress plugin repository

Readme.txt improvements

---

includes/object-cache.php

As there are separate connection methods now the options variable in the constructor it not set failing the test for the correct `info` command.
There might be a better approach to this populating the `info` property in the specific connection methods instead.

Connection error using predis with sentinel configuration

---

docker/start.sh

Might fix the currently broken method of deleting a line with a given constant name in it to load another docker configuration

OSX compat constant line deletion

---

dependencies/vendor/predis/predis/autoload.php
includes/object-cache.php

In 2.0.0 we introduced the following line relying on the return value of `require_once` to throw an exception: https://github.com/rhubarbgroup/redis-cache/blob/6036289b6273465347fd4a307e0dfb5f6940619c/includes/object-cache.php#L616
Not only can this construct not be used to determine if a file was loaded correctly as the file itself can return any value at any time but the evaluation of the return value happens after the loading process itself. If this loading process generates an error it will do so before the return value can be read.
To be backwards compatible I reintroduced the `dependencies/vendor/predis/predis/autoload.php` file and just let it return `false` in order for the connection method to throw and prompt the admin to update `object-cache.php`.
As a side note interpreting …

Fixed `require_once` error updating from version 2.0.0

---

assets/js/admin.js
includes/class-plugin.php

The dashboard widget now respects the `WP_REDIS_DISABLE_BANNERS` constant.
Also seized a chance to simplify the graph generation code fixing some inconsistencies in the process.

JS respect disable banners + simplification

---

docker/apf-template.php
docker/start.sh

You can now easily define the client to be used using the `-c` or the `--client` flag.
Example: `docker/start.sh -c credis replication`
Will update the wiki once this is merged.

Docker improvements

---

includes/object-cache.php

Re-using the `$parameters` variable is causing issues. Maybe an issue from the 2.x rewrite?
Resolves #250.

Fix non-instance Predis connection

---

includes/object-cache.php

Introduced in the latest refactoring: `wp_parse_url` is not yet available.
Also fixed the overview displaying `Array` instead of useful information.

Credis fatal error fix

---

CHANGELOG.md
readme.txt

Changed the `since` changelog entry for 2.0.13 to "all hooks" instead of "all functions"

Changelog clarification

---

includes/object-cache.php

Removed variable referencing in `connect_using_predis` method as it would cause fatals due to repeating referenced variable name `$connection_string` in consecutive `foreach` loops.

Fixed an error due to variable referencing

---

includes/class-plugin.php
includes/ui/diagnostics.php
redis-cache.php

Introduced `WP_REDIS_METRICS_MAX_TIME` constant to define the maximum time metrics should be collected. Default value is 1 hour. The dashboard widget always shows half an hour due to its size restriction.
This might be useful for external metrics collection as well (related: #271)
Constant so far not documented.

Metrics custom max time

---

includes/object-cache.php

Customizations for SpinupWP.com to easily rollout the full plugin, instead of a `object-cache.php` fork.

Customizations for Spinup WP

---

includes/class-plugin.php

Prevent performance data from being displayed when the debug is enabled but to the file only.

Fixed performance debugging

---

includes/object-cache.php

A `float` is put in it everywhere.

Fix cache time's type in WP_Object_Cache

---

includes/object-cache.php

The proposal is simple, add a new hook that reports statistics (hits & misses) for every cache call.
This enables end users to implement fine grained metrics in order to better understand cache runtime behaviour, in order to optimize cache usage.
The proposed signature is as follows:
```php
/**
* Fires on every cache call.
*
* This hook is called on every cache request.
* It reports statistics per key involved. @see WP_Object_Cache::TRACE_FLAG_READ and friends.
*
* @param  string             $command   The command that was executed.
* @param  string             $group     Key group.
* @param  array[string]array $keyValues Maps keys to the returned values (if any) and the resulting status.
*  $keyValues = [
*      "foo" => ["value" => "bar", "status" => TRACE_FLAG_READ | TRACE_FLAG_HIT], …
```

add 'redis_object_cache_trace' hook. Enables tracing of every call, useful for fine grained metric collection

---

includes/object-cache.php

The above code ensure a unique key salt prefix for customers hosting multiple sites on the same Cloudways server, the code checks if the site is hosted on a Cloudways environment along with if the WP_CACHE_KEY_SALT is defined in wp-config.php or not.  if key prefix is not defined and site is hosted on Cloudways the unique key-prefix will be set automatically by the plugin.

Set unique `WP_CACHE_KEY_SALT` for sites hosted on Cloudways

---

includes/diagnostics.php

If the plugin is disabled via `WP_REDIS_DISABLED`, then errors like this are thrown on the diagnostic page:
`An error of type E_ERROR was caused in line 127 of the file /path/to/redis-cache/includes/diagnostics.php`
`Error message: Uncaught TypeError: array_values(): Argument #1 ($array) must be of type array, null`
This prevents them.

fix: prevent errors on diagnostics page if the plugin is disabled

---

.github/workflows/tests.yml
includes/object-cache.php
tests/phpunit/bootstrap.php
tests/phpunit/cache/class-cache-test.php

This PR adds the ability to run the tests using github actions, instead of depending only on the Docker implementation.
Tests are done with the following matrix
- PHP 7.1 - 8.1
- Redis: 4,5,6 for single instance and 5,6 for clusters.

Implementing Github actions

---

CHANGELOG.md
includes/diagnostics.php
includes/object-cache.php

> **Warning**
> 1. This PR does no guarantee that the GH tests will pass (not yet).
> 2. I can't say I was able to test all the available scheme locally, but I know it works for `tcp`.
This PR is related to using `predis`/`phpredis` with `clusters`.
Related issues : 
- https://github.com/rhubarbgroup/redis-cache/issues/331
- https://wordpress.org/support/topic/ping-issue-on-cluster-connection/
<details>
<summary>Predis Diagnostics</summary>
```
Status: Connected
Client: Predis (v1.1.10)
Drop-in: Valid
Disabled: No
Ping: PONG
Errors: []
PhpRedis: 5.3.7
Relay: Not loaded
Predis: 1.1.10
Credis: Not loaded
PHP Version: 8.1.7
Plugin Version: 2.0.26
Redis Version: 6.2.0
Multisite: No
Metrics: Enabled
Metrics recorded: 46
Filesystem: Working
Global Prefix: "wp_"
Blog Prefix: "wp_" …
```

[WIP] fix the connectionID value when connecting to cluster

---

includes/object-cache.php

true not work..
true => 'predis'
AND 
wp-config.php
WP_REDIS_SERVERS
parameter : alias=master does not work. role=master & role=replica
ex) define( 'WP_REDIS_SERVERS',['tcp://127.0.0.1:6379?database=0&role=master','tcp://127.0.0.1:6380?database=0&role=replica']);

Replication bug

---

includes/object-cache.php

If a cache item has a value of "null", the current isset() mechanism returns false. This results in the cache key never being used and, in my case, hundreds of duplicate queries on each page load. This changes it to array_key_exists. Likewise, it would never delete the cache key, and probably other issues.

fix for when cache item's value is set to null

---

includes/object-cache.php

Related to #379.
`$cache` should be filled based on `$results`.

When retrieving multiple values ensure the results variable is properly set in case of an exception

---

includes/object-cache.php

Received an error when calling the `Redis->pipeline->exec` method, which may not return an array, resulting in the following log:
```
PHP Warning:  array_map(): Expected parameter 2 to be an array, bool given in /home/user/public_html/wp-content/object-cache.php on line 1212
PHP Warning:  array_combine() expects parameter 2 to be array, null given in /home/user/public_html/wp-content/object-cache.php on line 1214
PHP Warning:  Invalid argument supplied for foreach() in /home/user/public_html/wp-content/object-cache.php on line 1216
```
Added a result check to make sure we got an array to pass to the array_map function.

Fix array_map error with empty result of exec method

---

includes/class-qm-collector.php

The next release of Query Monitor will [switch to using a `QM_Data` instance for the data storage for each collector](https://github.com/johnbillion/query-monitor/pull/671). The class implements `ArrayAccess` so there's generally no need for third party collectors to change their behaviour, except in the case where they try to write to a second-level element within an array in which case an "Indirect modification of overloaded element of QM_Data_Fallback has no effect" PHP notice will be triggered because it's not possible to write to a property of an overloaded element.
Without this fix the code still works, it just doesn't report the figures for hits and misses. With this fix, all is well again.

Add support for the new storage classes in Query Monitor

---

includes/ui/tabs/overview.php

Reported here: https://wordpress.org/support/topic/php-warning-379/
```
PHP Warning: The use statement with non-compound name ‘WP_Error’ has no effect in redis-cache/includes/ui/tabs/overview.php on line 10
```

Fix `WP_Error` warning

---

.github/workflows/tests.yml

v5 was dropped
https://github.com/Grokzen/docker-redis-cluster/commit/d597529abb5d9e8b02721c7a2a690f7100fd67e8
https://hub.docker.com/r/grokzen/redis-cluster/tags

Fix grokzen/redis-cluster Docker image

---

includes/ui/settings.php

The [Ymir](https://ymirapp.com) runtime doesn't use the PhpRedis extension and only [Relay](https://relay.so). The upsell for OCP says that the environment isn't compatible because PhpRedis extension is missing, but that's not the case.

Add Relay extension check for OCP compatibility check

---

includes/object-cache.php

Example:
```
$group = "group1"
$this->blog_prefix = "1"
$salt is "\*:group\*:\*" but should be "\*:group1:\*"
```

Fix `$salt` when `$group` ends with site id

---

README.md
includes/diagnostics.php
includes/object-cache.php

Simple fix to allow a WP_REDIS_SSL setting to pass SSL connection arguments in the case of a TLS service (such as Heroku) that needs additional SSL parameters.
`connect_using_phpredis()` sets an 'ssl' key on it's connection arguments derived from it via `$parameters['ssl']`, `connect_using_predis()` directly uses the `$parameters['ssl']` value.
e.g.
```php
define('WP_REDIS_SSL', [
'verify_host' => false,
'verify_peer' => false,
'verify_peer_name' => false,
]);
```

Add WP_REDIS_SSL setting, pass to predis and phpredis

---

includes/class-plugin.php
includes/object-cache.php

Currently, the statistics are always formatted in the default format, which usually is English. This pull request uses `number_format_i18n` to format the statistics according to the current locale.

Format statistcs according to current locale

---

includes/ui/settings.php

Currently, the headline of the Pro advertising is not translatable. This pull request fixes this and allow its translation.

Allow translation of Object Cache Pro headline

---

includes/class-plugin.php
includes/ui/settings.php

This PR changes the way plugin detects if it was installed by AccelerateWP. It relies on specific value of constants `WP_REDIS_PATH` and `WP_REDIS_SCHEME`.
It also makes settings screen and links in the plugins list respect the `WP_REDIS_DISABLE_BANNERS` constant.

Update check if plugin was installed by AccelerateWP

---

includes/class-plugin.php
includes/ui/settings.php

Changes the logic for displaying Object Cache PRO banners on the settings page and in the plugins' list. Constant `WP_REDIS_DISABLE_BANNERS` now affects visibilities of these banners only for AccelerateWP installs.

Update banner visibility rules for AccelerateWP installs.

---

includes/object-cache.php

This pull requests changes the behaviour of caching functions that utilize Redis pipeline to execute multiple commands in batch. When the pipeline returns unexpected results, it no longer logs an error, but discard the current transaction and returns an empty array.

Handle unexpected result from Redis pipeline quietly.

---

README.md

As mentioned here: https://github.com/rhubarbgroup/redis-cache/issues/402#issuecomment-1330457389 and confirmed locally.

Update README.md to use correct parameters for master/replica connection

---

CHANGELOG.md
redis-cache.php

When using this as a must-use plugin, developers must define `WP_REDIS_PLUGIN_PATH` so the drop-in can locate files. The main plugin file also defines this constant, but without checking if it's already been defined, triggering PHP warnings.
Check if constant is defined before defining it, to avoid warnings.

Check if WP_REDIS_PLUGIN_PATH is defined before defining

---

CHANGELOG.md
includes/object-cache.php

Resolves #507
Try to load plugin textdomain and if failed override locale and options loading to not crash

Fix issue with loading translated error messages in show_error_and_die

---

includes/object-cache.php

This is necessary when connecting to a REDIS cluster that requires an ssl context (e.g. AWS Elasticache serverless)

adds support for ssl context in redis clusters

---

CHANGELOG.md
includes/object-cache.php

Resolves #519
When using Predis with replication connection we can't get/set flush timeout directly but we need to get master connection and work with it.

Fixed  issue with Predis and replication connection

---

CHANGELOG.md
includes/object-cache.php

The first commit just suppress warning when Redis server version couldn't be determined with `INFO` command.
In the second commit I tried to get `INFO` results from the master node for `MasterSlaveReplication` connection

Fix Redis version determination for predis replication connection

---

CHANGELOG.md
includes/class-predis.php

Fixes #527
CLI command uses Predis client to flush cache after enable/disable plugin. Changes in this PR allows to proper iterate over cluster nodes and execute `flushdb` command.

Fix Predis cluster flush

---

CHANGELOG.md
README.md
includes/class-plugin.php

Couldn't find a CONTRIBUTING.md (i may be blind) so took a best guess. Also just assumed 2.6 but who knows?!
I think this could easily be a thing that gets enhanced deeper for multisite to allow individual site owners to flush their individual sites cache or something along those lines... but this probably serves my needs well enough :D

Add filter to allow customizing who can flush the cache

---

includes/object-cache.php

Fixes #543
With this change `wp cache flush` works for me for all configurations from https://github.com/rhubarbgroup/redis-cache?tab=readme-ov-file#scaling
I hope this time it will fix issue for users :crossed_fingers: :smiley:

Swith to master before fetching info for predis with replicated connections

---

includes/object-cache.php

This fix is related to [543#issuecomment-2558071224](https://github.com/rhubarbgroup/redis-cache/issues/543#issuecomment-2558071224)

Switch back to node which were used before fetching info

---

includes/object-cache.php

`$node` can't be set without `$connection` but PhpStan highlights this as error

Fix PhpStan warning

---

includes/object-cache.php

Fixes #574 
When serializer enabled Redis can't increment/decrement value because it becomes non-numeric after serializing so in this PR I replaced incrBy/decrBy calls with sequence of get + set commands

Replace incrBy/decrBy with get+set
