includes/object-cache.php

Added support for $found parameter according to
https://wordpress.org/support/topic/boolean-values

Added support for $found parameter

---

includes/object-cache.php

This is similar to the  get/set actions (and get filter) already added in a previous update. 
Just adds a matching action for delete. 
Personally I need this for my logging system that tracks actions and specifically because my 'set' action triggers delete commands and I need them logged to. 
Don't think there's any real risk to adding this and it would be very useful for me. 
Thanks!

update ::delete() with redis_object_cache_delete action

---

includes/object-cache.php

Handle Redis connection failure gracefully.

---

redis-cache.php

https://github.com/tillkruss/redis-cache/issues/131#issuecomment-558905122

cleans up cluttered cron schedule

---

includes/object-cache.php

Added object cloning before local in-memory cache insertion as per https://github.com/tillkruss/redis-cache/issues/140

Added object cloning for the in-memory cache

---

includes/object-cache.php

Based on @timofeycom's patch from #146.

Add TLS support

---

CHANGELOG.md
includes/object-cache.php
readme.txt
redis-cache.php

Thank you for the quick turnaround.

Add missing variable assignment

---

includes/object-cache.php
phpcs.xml

Tweaked PHPCS rules

---

includes/object-cache.php

fixed logic error

---

phpcs.xml

+ resolved some formatting issues

Coding Standards changed min PHP version

---

includes/class-autoloader.php
includes/class-plugin.php
includes/class-servers-list.php
includes/cli/class-commands.php
redis-cache.php

Needed to rename `plugin.php` as it had no `class-` prefix before.

Added autoloader

---

includes/ui/admin-page.php

Changed occurrences of `__` or `_e` to their HTML-escaping counterparts if applicable used `wp_kses_post` otherwise.

Admin page XSS protections

---

includes/object-cache.php

Redis returns an error if we use the `SET` command with the `EX` flag if the expiry is 0.
This change alters the call if expiry is not set or is 0.

Fix EX flag while expiry=0

---

README.md
readme.txt

Fixed the link to the configuration parameters wiki page.

Corrected config options wiki link

---

includes/class-qm-collector.php
includes/class-qm-output.php
includes/cli/class-commands.php
includes/object-cache.php
includes/ui/diagnostics.php
includes/ui/query-monitor.php
includes/ui/settings.php
includes/ui/widget.php

Should prevent every file from being called outside of the WordPress context using direct URLs.

Added ABSPATH checks

---

assets/js/admin.js
includes/class-plugin.php

- added jQuery event namespacing `click.redis`
- added the ability to use a non WP-standard jQuery version
- used jQuery.extend to extend the chart defaults while creating the different charts
- mostly rely on one object in the global context
- moved the UI-facing function executions to the bottom
- wrapped all in a closure to avoid conflicts

JS refactoring to increase compatibility and reduce size

---

assets/css/admin.css
assets/js/admin.js
includes/class-plugin.php
includes/class-ui.php
includes/ui/settings.php
includes/ui/tabs/diagnostics.php
includes/ui/tabs/metrics.php
includes/ui/tabs/overview.php

Added tab functionality and moved the Pro promotion to a dedicated sidebar.
Styling heavily inspired by Yoast SEO

Settings page tabs

---

docker/start.sh

Might resolve #213 
Needs testing on OSX

refactor apf function

---

includes/class-plugin.php

Added checks for successfully established Redis connection before displaying metrics and recording them.

Fixed metrics collection error

---

docker/apf-template.php
docker/wordpress/app-entrypoint-custom.sh

Added Query Monitor and set some dev specific constants to better detect errors developing using the docker environment.

Docker improvements

---

dependencies/vendor/predis/predis/autoload.php

Re-added predis autoload stub

---

includes/class-plugin.php
includes/object-cache.php
includes/ui/diagnostics.php

Let me know if we should use the shorthand `[ 1, 2, 3 ]` (this PR) or the old `array( 1, 2, 3 )`.
Either way we should consistently use one of them.

Changed all array definitions to shorthand style

---

includes/class-plugin.php
includes/object-cache.php
includes/ui/class-tab.php

Updated https://github.com/rhubarbgroup/redis-cache/wiki/Hook-reference aswell

Added @since to hook comments

---

includes/cli/class-commands.php

Fixed variable instance naming in CLI context

---

.gitattributes
phpcs.xml

Introduced some phpcs settings from the `wp scaffold plugin-tests` command.
+ defined line endings in `.gitattributes` file to help me and any other contributor on windows :wink:

Coding style improvements

---

includes/object-cache.php

Inspired by #270 I have added a cache key map to avoiding consecutive builds of already built redis cache keys.

Cache key map

---

includes/class-plugin.php
includes/ui/settings.php

As per https://wordpress.org/support/topic/redis-cache-pro-box-not-translatable/

Pro version ad translation

---

includes/class-plugin.php

Fixed textdomain loading too early

---

assets/js/admin.js
includes/class-metrics.php
includes/class-plugin.php

Will close #223 
Will save a serialized object of the new metrics class instead of the non standardized string to redis. Ignores entries saved using prior versions.
PS: Precursor to REST API (work in progress)

Dedicated metrics class

---

includes/class-metrics.php

`class-metrics.php` is namespaced.

Fix Exception's namespace

---

includes/object-cache.php

Please see https://www.php.net/manual/en/function.isset.php

isset() does not allow null

---

includes/class-metrics.php

Fix https://github.com/rhubarbgroup/redis-cache/issues/308
This is my first PR, say me if anything can be done better :)

Securely way to test WP_REDIS_DISABLE_METRICS 

---

docker-compose.yml
docker/redis-sentinel/docker-entrypoint.sh
docker/start.sh
docker/wordpress/Dockerfile
docker/wordpress/app-entrypoint-custom.sh

Wanted to start developing again and well ... docker dev environments needed some encouragement due to config and API changes in the redis and bitnami WordPress containers.
Tested using Win10 / WSL 2 - Ubuntu 20.04 - Docker 20.10.7 - Bash 5.0.17

Docker Improvements 2021 Edition

---

.github/workflows/tests.yml
tests/phpunit/bootstrap.php

> **Warning**
> This PR does not guarantee that the tests will pass, as I am still trying to figure out a way to run them locally with ease.
This PR reduces the number of tests executed, while also provide more configuration and make sure the cluster setup works.

Reduce the number of tests

---

includes/object-cache.php

This PR rewrite the `add_multiple` and `set_multiple`

Enhance `add_multiple` & `set_multiple` functionality

---

.github/workflows/tests.yml

@tillkruss Six less test runs!

Remove unused Redis version from CI

---

includes/object-cache.php

This ability explained in https://github.com/phpredis/phpredis/blob/develop/cluster.markdown#loading-a-cluster-configuration-by-name

The ability passing a named redis cluster connection parameters is added

---

includes/object-cache.php

... instead of `$this->redis instanceof Predis\Client`
@tillkruss Here we go.
Closes #366

Add is_predis method

---

includes/class-plugin.php
includes/object-cache.php
includes/ui/query-monitor.php
includes/ui/tabs/overview.php
includes/ui/widget.php
phpstan-baseline.neon
phpstan.neon.dist

Fix few more PHPStan errors

---

.editorconfig

Improve EC config

---

.editorconfig
.github/workflows/lint.yml
includes/class-plugin.php
includes/object-cache.php
phpcs.xml
phpstan-baseline.neon
phpunit.xml.dist
readme.txt

@tillkruss #390 was half-done and ❌failing.

Really fix all EC problems

---

.github/workflows/lint.yml
.gitignore
composer.json
includes/class-plugin.php
includes/class-qm-output.php
includes/diagnostics.php
phpstan-baseline.neon
phpstan.neon.dist
tests/PHPStan/query-monitor-stubs.php

Improve static analysis

---

readme.txt

viktor is the release checklist robodog 🤖🐶

Fix version in readme.txt

---

FAQ.md
INSTALL.md
README.md
includes/diagnostics.php
readme.txt

Better documentation

---

CHANGELOG.md
README.md
includes/class-plugin.php

Resolves #428 
https://user-images.githubusercontent.com/1422996/223417430-b9b176b3-e81b-4329-bb8d-c59b0f423674.mp4

Admin bar improvements

---

CHANGELOG.md
includes/class-plugin.php
includes/ui/settings.php

Tweak links when Accelerate WP is enabled

---

assets/js/admin.js
includes/class-plugin.php

Don't redirect to settings on flushing Redis cache

---

CHANGELOG.md
includes/class-plugin.php
includes/class-predis.php
includes/cli/class-commands.php
includes/object-cache.php
includes/ui/tabs/overview.php
phpstan.dist.neon

Prevent first time critical errors

---

.github/workflows/lint.yml

From https://github.com/rhubarbgroup/redis-cache/commit/977d79d536631f7fb5a5cae2f26d1ca810a02afa

Run CI on PHP 7.2 too

---

includes/class-plugin.php

Contains a refactor of `Plugin::acceleratewp_install()` to take the `WP_REDIS_DISABLE_BANNERS` constant into account.

Refactor AccelerateWP installation check.

---

.github/workflows/lint.yml

Prevent bug in latest release.
Takes 3 extra seconds.

Check source code for syntax errors in CI

---

FAQ.md
includes/object-cache.php

Found two misspellings.
This can be automated!

Fix two typos

---

phpstan.dist.neon

Run PHPStan on the plugin main file too

---

phpstan.dist.neon
tests/PHPStan/bootstrap.php

@tillkruss The comment made me do this.

Actually test for ext-relay while running PHPStan

---

includes/object-cache.php

If set use value of `WP_REDIS_FLUSH_TIMEOUT` when flush cache
TODO: get/set timeout helpers should be added to Predis
Closes #510
Closes #508
Closes #514

Respect WP_REDIS_FLUSH_TIMEOUT

---

CHANGELOG.md
includes/object-cache.php

Fixes #531
Error may be reproduced when Redis server is not reachable

Fixed loading textdomain in show_error_and_die

---

README.md
includes/object-cache.php

Introduce WP_REDIS_DISABLE_GROUP_FLUSH to disable group flushing

---

CHANGELOG.md
includes/object-cache.php

Fetch Redis server info for sentinel replicated connections

---

includes/class-predis.php
includes/object-cache.php

Fixes https://github.com/predis/predis/issues/1474

Respect WP_REDIS_SCHEME for cluster connection

---

readme.txt

fix cs in readme.txt

---

includes/class-plugin.php
includes/object-cache.php

Disable `Squiz.PHP.Heredoc.NotAllowed` before heredoc

Suppress Squiz.PHP.Heredoc.NotAllowed warning
